CREATE TABLE "month" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "month_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"number" integer,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"sgk5510_employee_share_rate" numeric(6, 4) DEFAULT 0.14,
	"sgk5510_employee_unemployment_share_rate" numeric(4, 2) DEFAULT 0.01,
	"sgk5510_employer_share_rate" numeric(6, 4) DEFAULT 0.2175,
	"sgk5510_employer_unemployment_share_rate" numeric(4, 2) DEFAULT 0.03,
	"sgk5746_employer_share_rate" numeric(6, 4) DEFAULT 0.2175,
	"sgk5746_employer_unemployment_share_rate" numeric(4, 2) DEFAULT 0.02,
	"income_tax_sgk5746_employee_share_rate" numeric(4, 2) DEFAULT 0.14,
	"income_tax_sgk5746_employee_unemployment_share_rate" numeric(4, 2) DEFAULT 0.01,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "month_workers" (
	"month_id" integer NOT NULL,
	"project_id" integer,
	"worker_id" integer NOT NULL,
	"hour_definition_id" integer NOT NULL,
	"arge_center_work_days" integer DEFAULT 0,
	"other_activities_work_days" integer DEFAULT 0,
	"total_work_days" integer DEFAULT 0,
	"gross_base_salary" numeric(15, 2) DEFAULT 0,
	"overtime_additional_pay" numeric(15, 2) DEFAULT 0,
	"income_tax_amount" numeric(15, 2) DEFAULT 0,
	"agi" numeric(15, 2) DEFAULT 0,
	"argeExemptionRate" numeric(6, 4) DEFAULT 0,
	"monthly_upper_limit" numeric(15, 2) DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "month_workers_month_id_worker_id_pk" PRIMARY KEY("month_id","worker_id")
);
--> statement-breakpoint
ALTER TABLE "project" DROP CONSTRAINT "project_connection_id_connection_id_fk";
--> statement-breakpoint
ALTER TABLE "project_workers" DROP CONSTRAINT "project_workers_hour_definition_id_hour_definition_id_fk";
--> statement-breakpoint
ALTER TABLE "project" ADD COLUMN "title" text NOT NULL;--> statement-breakpoint
ALTER TABLE "project" ADD COLUMN "date" date NOT NULL;--> statement-breakpoint
ALTER TABLE "project" ADD COLUMN "active" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "month_workers" ADD CONSTRAINT "month_workers_month_id_month_id_fk" FOREIGN KEY ("month_id") REFERENCES "public"."month"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "month_workers" ADD CONSTRAINT "month_workers_project_id_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "month_workers" ADD CONSTRAINT "month_workers_worker_id_worker_id_fk" FOREIGN KEY ("worker_id") REFERENCES "public"."worker"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "month_workers" ADD CONSTRAINT "month_workers_hour_definition_id_hour_definition_id_fk" FOREIGN KEY ("hour_definition_id") REFERENCES "public"."hour_definition"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "name";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "number";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "start_date";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "end_date";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "connection_id";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "sgk5510_employee_share_rate";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "sgk5510_employee_unemployment_share_rate";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "sgk5510_employer_share_rate";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "sgk5510_employer_unemployment_share_rate";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "sgk5746_employer_share_rate";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "sgk5746_employer_unemployment_share_rate";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "income_tax_sgk5746_employee_share_rate";--> statement-breakpoint
ALTER TABLE "project" DROP COLUMN "income_tax_sgk5746_employee_unemployment_share_rate";--> statement-breakpoint
ALTER TABLE "project_workers" DROP COLUMN "hour_definition_id";--> statement-breakpoint
ALTER TABLE "project_workers" DROP COLUMN "arge_center_work_days";--> statement-breakpoint
ALTER TABLE "project_workers" DROP COLUMN "other_activities_work_days";--> statement-breakpoint
ALTER TABLE "project_workers" DROP COLUMN "total_work_days";--> statement-breakpoint
ALTER TABLE "project_workers" DROP COLUMN "gross_base_salary";--> statement-breakpoint
ALTER TABLE "project_workers" DROP COLUMN "overtime_additional_pay";--> statement-breakpoint
ALTER TABLE "project_workers" DROP COLUMN "income_tax_amount";--> statement-breakpoint
ALTER TABLE "project_workers" DROP COLUMN "agi";--> statement-breakpoint
ALTER TABLE "project_workers" DROP COLUMN "argeExemptionRate";--> statement-breakpoint
ALTER TABLE "project_workers" DROP COLUMN "monthly_upper_limit";