CREATE TABLE "worker_tally" (
	"worker_id" integer NOT NULL,
	"month_id" integer NOT NULL,
	"ucretturu" text,
	"toplamsigortagun" numeric(15, 2) DEFAULT 0,
	"argefaaliyetgunsayisi" numeric(15, 2) DEFAULT 0,
	"argegelirvergisigunsayisi" numeric(15, 2) DEFAULT 0,
	"aylikbrutkazanc" numeric(15, 2) DEFAULT 0,
	"argebrutucret" numeric(15, 2) DEFAULT 0,
	"argebrutkazancfarki" numeric(15, 2) DEFAULT 0,
	"toplamiscisskprimtutari" numeric(15, 2) DEFAULT 0,
	"issizlikiscipayitutari" numeric(15, 2) DEFAULT 0,
	"gelirvergisimatrahi" numeric(15, 2) DEFAULT 0,
	"argegelirvergisimatrahi" numeric(15, 2) DEFAULT 0,
	"artigvmatrahi" numeric(15, 2) DEFAULT 0,
	"gelirvergisitutari" numeric(15, 2) DEFAULT 0,
	"argegelirvergisitutari" numeric(15, 2) DEFAULT 0,
	"gvistisnatutari" numeric(15, 2) DEFAULT 0,
	"asgariucretgvistisnasi" numeric(15, 2) DEFAULT 0,
	"argeasgariucretgvistisnasi" numeric(15, 2) DEFAULT 0,
	"asgariucretdvistisnasi" numeric(15, 2) DEFAULT 0,
	"argeasgariucretdvistisnasi" numeric(15, 2) DEFAULT 0,
	"odenecekgelirvergisi" numeric(15, 2) DEFAULT 0,
	"damgavergisitutari" numeric(15, 2) DEFAULT 0,
	"odenecekdamgavergisi" numeric(15, 2) DEFAULT 0,
	"ayliknetkazanc" numeric(15, 2) DEFAULT 0,
	"mahsupedilecekagi" numeric(15, 2) DEFAULT 0,
	"issizlikisverenpayitutari" numeric(15, 2) DEFAULT 0,
	"toplamisverensskprimtutari" numeric(15, 2) DEFAULT 0,
	"icratutari" numeric(15, 2) DEFAULT 0,
	"nafakatutari" numeric(15, 2) DEFAULT 0,
	"bes_kesinti_tutari" numeric(15, 2) DEFAULT 0,
	"yemekyardiminet" numeric(15, 2) DEFAULT 0,
	"yemekyardimibrut" numeric(15, 2) DEFAULT 0,
	"isverenhastalikprimtutari" numeric(15, 2) DEFAULT 0,
	"isverenihtiyarlikprimtutari" numeric(15, 2) DEFAULT 0,
	"isverenanalikprimtutari" numeric(15, 2) DEFAULT 0,
	"isverentehlikederecesiprimtutari" numeric(15, 2) DEFAULT 0,
	"uzunvadeliskisveren" numeric(15, 2) DEFAULT 0,
	"gssisveren" numeric(15, 2) DEFAULT 0,
	"kisavadeliskisveren" numeric(15, 2) DEFAULT 0,
	"sgk_6111kanunindirimi" numeric(15, 2) DEFAULT 0,
	"kisavadeliskisveren_muafiyettutari" numeric(15, 2) DEFAULT 0,
	"uzunvadeliskisveren_muafiyettutari" numeric(15, 2) DEFAULT 0,
	"gssisveren_muafiyettutari" numeric(15, 2) DEFAULT 0,
	"artiisverendevlettesviki" numeric(15, 2) DEFAULT 0,
	"sgk_4447kanunindirimi" numeric(15, 2) DEFAULT 0,
	"sgk_16322kanunindirimi" numeric(15, 2) DEFAULT 0,
	"sgk_26322kanunindirimi" numeric(15, 2) DEFAULT 0,
	"sgk_7252kanunindirimi" numeric(15, 2) DEFAULT 0,
	"sgk_3294kanunindirimi" numeric(15, 2) DEFAULT 0,
	"sgk_2828kanunindirimi" numeric(15, 2) DEFAULT 0,
	"isvozelsagliksigortasibrut" numeric(15, 2) DEFAULT 0,
	"isvozelsagliksigortasinet" numeric(15, 2) DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "worker_tally_worker_id_month_id_pk" PRIMARY KEY("worker_id","month_id")
);
--> statement-breakpoint
ALTER TABLE "worker_tally" ADD CONSTRAINT "worker_tally_worker_id_worker_id_fk" FOREIGN KEY ("worker_id") REFERENCES "public"."worker"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "worker_tally" ADD CONSTRAINT "worker_tally_month_id_month_id_fk" FOREIGN KEY ("month_id") REFERENCES "public"."month"("id") ON DELETE cascade ON UPDATE no action;