import type { DiaFilter } from "../types/dia-requests.js";

export const URL_BASE = "ws.dia.com.tr/api/v3";

export const ONLY_ACTIVE_FILTER: DiaFilter = {
  field: "durum",
  operator: "=",
  value: "A",
};

export const workerTallySelectedColumns = [
  "_key_per_personel",
  "muhasebelesme",
  "duzenlemetarihi",
  "persdepartmanaciklama",
  "adi",
  "soyadi",
  "tckimlikno",
  "sube",
  "gorevi",
  "ucretturu",
  "toplamsigortagun",
  "argefaaliyetgunsayisi",
  "argegelirvergisigunsayisi",
  "aylikbrutkazanc",
  "argebrutucret",
  "argebrutkazancfarki",
  "toplamiscisskprimtutari",
  "issizlikiscipayitutari",
  "gelirvergisimatrahi",
  "argegelirvergisimatrahi",
  "artigvmatrahi",
  "gelirvergisitutari",
  "argegelirvergisitutari",
  "gvistisnatutari",
  "asgariucretgvistisnasi",
  "argeasgariucretgvistisnasi",
  "asgariucretdvistisnasi",
  "argeasgariucretdvistisnasi",
  "odenecekgelirvergisi",
  "damgavergisitutari",
  "odenecekdamgavergisi",
  "ayliknetkazanc",
  "mahsupedilecekagi",
  "issizlikisverenpayitutari",
  "toplamisverensskprimtutari",
  "icratutari",
  "nafakatutari",
  "bes_kesinti_tutari",
  "carifisno",
  "yemekyardiminet",
  "yemekyardimibrut",
  "isverenhastalikprimtutari",
  "isverenihtiyarlikprimtutari",
  "isverenanalikprimtutari",
  "isverentehlikederecesiprimtutari",
  "uzunvadeliskisveren",
  "gssisveren",
  "kisavadeliskisveren",
  "sgk_6111kanunindirimi",
  "kisavadeliskisveren_muafiyettutari",
  "uzunvadeliskisveren_muafiyettutari",
  "gssisveren_muafiyettutari",
  "artiisverendevlettesviki",
  "sgk_4447kanunindirimi",
  "sgk_16322kanunindirimi",
  "sgk_26322kanunindirimi",
  "sgk_7252kanunindirimi",
  "sgk_3294kanunindirimi",
  "sgk_2828kanunindirimi",
  "isvozelsagliksigortasibrut",
  "isvozelsagliksigortasinet",
];
